#pragma once

// From glfw3.h
#define SOLAR_MOUSE_BUTTON_1         0
#define SOLAR_MOUSE_BUTTON_2         1
#define SOLAR_MOUSE_BUTTON_3         2
#define SOLAR_MOUSE_BUTTON_4         3
#define SOLAR_MOUSE_BUTTON_5         4
#define SOLAR_MOUSE_BUTTON_6         5
#define SOLAR_MOUSE_BUTTON_7         6
#define SOLAR_MOUSE_BUTTON_8         7
#define SOLAR_MOUSE_BUTTON_LAST      SOLAR_MOUSE_BUTTON_8
#define SOLAR_MOUSE_BUTTON_LEFT      SOLAR_MOUSE_BUTTON_1
#define SOLAR_MOUSE_BUTTON_RIGHT     SOLAR_MOUSE_BUTTON_2
#define SOLAR_MOUSE_BUTTON_MIDDLE    SOLAR_MOUSE_BUTTON_3
